<?php

namespace MainBundle\Repository;

/**
 * EnqueteRepository (Test)
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnqueteRepository extends \Doctrine\ORM\EntityRepository
{
//    public function getChoicesFromQuestions()
//    {
//        $qb = $this->getEntityManager()->createQueryBuilder();
//        $qb->select('question')
//            ->from('\MainBundle\Entity\Question', 'q')
//            ->join('q.choices', 'c')
//            ->where('q.enqueteId' );
//
//
//        return $qb->getQuery()->getResult();
//    }
}

