<?php

namespace MainBundle\Repository;

/**
 * FractieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FractieRepository extends \Doctrine\ORM\EntityRepository
{
}
