<?php

namespace MainBundle\Repository;

/**
 * RaadswerkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaadswerkRepository extends \Doctrine\ORM\EntityRepository
{
}
