<?php

namespace MainBundle\Repository;

/**
 * StandpuntenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StandpuntenRepository extends \Doctrine\ORM\EntityRepository
{
}
