services:
#    main.example:
#        class: MainBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.form.registration:
        class: MainBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.form.profile:
        class: MainBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: app_user_profile }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }